---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Plantilla para implementar un Bucket en S3"
Resources:
  s3Bucket:                                              
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: "lab545415487687"
      Tags:
        - Key: "indentificador"
          Value: "bucket_Cloudformation"

# Estoy usando la extension de CloudFormation en VisualStudio para facilitar trabajo
# Estoy probando el uso de etiquetas

# Comando para validar mi template
  #aws cloudformation validate-template --template-body file://<Nombre_plantilla.yaml>
  # "Como salida se tiene que observar que: "Parameters: []""

#Comando para lanzar mi template
  #aws cloudformation create-stack --stack-name <Nombre_stack> --template-body file://<Nombre_plantilla.yaml> 
  # "Como salida se tiene que observar: StackId: arn:aws:cloudformation: <-- el ARN del Satck"

# Comando para listar solo los nombres de los stacks en cloudformation
  #aws cloudformation describe-stacks --query "Stacks[*].StackName" --output text

# Comando para borrar una Stack
  #aws cloudformation delete-stack --stack-name MiStack ("No recibes confirmación ")



#$Host.Name ==> comando para ver en que tipo de terminal de windows estoy 
  # "Me indica que estoy utilizando el símbolo del sistema estándar de Windows (cmd.exe)"


#CONLUCIONES:
#Puedo observar que la instancia se lanzo sin ningún nombre, Veré más adelante cómo asignarle un nombre por defecto
#No me gusta que no reciba ninguna confirmacion de lo que se esta haciendo (A comparacion de Terraform)